FROM python:3.13-slim

WORKDIR /app

COPY ../pyproject.toml .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -e .[dev]

COPY ../src/ ./src/

ENV PYTHONPATH=/app/src
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

EXPOSE 8000

CMD ["uvicorn", "src.jis.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
