FROM python:3.13-slim

WORKDIR /app

COPY pyproject.toml .
RUN pip install -e .[dev]

COPY ../src/ ./src/

EXPOSE 8000 5678

CMD ["uvicorn", "src.jis.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
